### ISSUE TITLE
[Suggestion] Bump iwyu version to 0.20

### ISSUE THREAD

**Issue by kyle-figure** [storypku/bazel_iwyu#7]
Any chance you can release a new bazel_iwyu package with iwyu 0.20? It includes a fix for crashes due to cycles in mappings. This fix allows for use of iwyu with many Boost libraries that happen to have cycles in their includes. Release notes: https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.20

If there is something I can do to help with the release, let me know.

**Comment by storypku** [comment]
Hi @kyle-figure ,
    Support for IWYU 0.20 was merged now. Thanks for your contribution, it inspires me. I made a little adjustment to your original dockerfile as it seems apt llvm repo is not ready for Ubuntu 22.04 at the moment.
